name: pyodide-kernel
channels:
  - conda-forge
  - https://repo.mamba.pm/emscripten-forge
dependencies:
  - python=3.11
  - cytoolz
  - dustgoggles
  - more_itertools
  - multidict
  - pillow
  - matplotlib  